{% set name = "beanie" %}
{% set version = "1.11.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roman-right/beanie/archive/refs/tags/{{ version }}.tar.gz
  sha256: b83005e9ef1b3db949d53ff2571acfbef4b4348bf60b3ab5c65c2eaa594bdd26

build:
  entry_points:
    - beanie = beanie.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.9.0
    - python >=3.6
    - toml
    - yarl >=1.6

test:
  imports:
    - beanie
  commands:
    - pip check
    - beanie --help
  requires:
    - pip

about:
  home: https://roman-right.github.io/beanie/
  dev_url: https://github.com/roman-right/beanie
  summary: Asynchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
